name: smart_time
description: A smart time management app with AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # 状态管理
  provider: ^6.1.1
  
  # 本地存储 & 工具
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # UI 组件
  table_calendar: ^3.1.0
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  
  # AI 模型
  google_generative_ai: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true